#!/usr/bin/perl


use DBIx::Cookbook::RDBO;
my $app = DBIx::Cookbook::RDBO;

$app->run;


=head1 NAME

rdbo_cmd - run Rose::DB::Object cookbook examples

=head1 SYNOPSIS

  ./scripts/rdbo_cmd subquery

=head1 DESCRIPTION

This script C<use>s L<DBIx::Cookbook::RDBO> which makes use of
C<MooseX::App::Cmd> to provide a modular command-line interface to a
number of shell scripts.

It leverages L<DBIx::Cookbook::DBH>.

=cut
