#!/usr/bin/perl

use Rose::DB::Object::Loader;

use DBIx::Cookbook::DBH;

use strict;
use warnings;

my $loader = 

my $dump_dir="$ENV{DBIX_COOK}/lib";
my $c = DBIx::Cookbook::DBH::connect_data;

make_schema_at 
  ( 
   'DBIx::Cookbook::DBIC::Sakila',
   {
    debug => 1, 
    dump_directory => $dump_dir,
    },
   [
    $c->{dsn}, $c->{user}, $c->{pass}
    ]
  );


=head1 NAME

dbic_loader - a script to create a DBIx::Class schema 

=head1 SYNOPSIS

  ./scripts/dbic_loader

=head1 DESCRIPTION

The C<scripts> directory of the distribution contains F<dbic_loader>, a script
which runs L<DBIx::Class::Schema::Loader> on the Sakila instance to build the
schema classes.

It leverages L<DBIx::Cookbook::DBH>.
