#!/usr/bin/env perl

use Rose::DB::Object::Loader;

use DBIx::Cookbook::DBH;
use DBIx::Cookbook::RDBO::RoseDB;

use strict;
use warnings;

my $loader = Rose::DB::Object::Loader->new
  (
   db => DBIx::Cookbook::RDBO::RoseDB->new('default'),
   class_prefix => 'Sakila',
   base_class => 'DBIx::Cookbook::RDBO::Sakila'
   );

my $dump_dir="$ENV{DBIX_COOK}/lib/DBIx/Cookbook/RDBO";

$loader->make_modules
  (
   module_dir => $dump_dir,

  );

#    module_postamble =><<EOCODE
# use Rose::DB::Object::Helpers qw(as_tree);
# EOCODE


=head1 NAME

dbic_loader - a script to create a DBIx::Class schema 

=head1 SYNOPSIS

  ./scripts/dbic_loader

=head1 DESCRIPTION

The C<scripts> directory of the distribution contains F<dbic_loader>, a script
which runs L<DBIx::Class::Schema::Loader> on the Sakila instance to build the
schema classes.

It leverages L<DBIx::Cookbook::DBH>.
