
=pod

=head1 NAME

DBIx::Cookbook::Recipe::Searching::complex_where - fairly complex WHERE clause

=head1 DESCRIPTION

Execute the following query:

  SELECT * FROM film 
  WHERE
    (DESCRIPTION LIKE 'drama%' AND title LIKE 'bikini%')
     OR
    title = 'BANG KWAI'

Sample Usage:

  ${orm}_cmd complex_where    # orm = dbic, skinny, rose, etc

=head1 RECIPES

=head2 DBIx::Class

    package DBIx::Cookbook::DBIC::Command::complex_where;
    use Moose;
    extends qw(MooseX::App::Cmd::Command);
    
    use Data::Dumper;
    
    sub execute {
      my ($self, $opt, $args) = @_;
    
    
     $self->app->schema->storage->debug(1);
    
      my $rs = do {
    
        my $where = 
          {
           -or => [
    	       -and => [
    			description => { 'like' , '%drama%' },
    			title => { 'like', 'bikini%' }
    		       ],
    	       title => 'BANG KWAI'
    	      ]
          };
    
        my $attr = { order_by => 'title' };
    
        $self->app->schema->resultset('Film')->search($where, $attr);
    
      };
    
      while (my $row = $rs->next) {
        my %data = $row->get_columns;
        warn Dumper(\%data);
      }
    
    }
    
    1;


=head2 DBIx::Custom

    package DBIx::Cookbook::Custom::Command::complex_where;
    use Moose;
    extends qw(MooseX::App::Cmd::Command);
    
    with 'DBIx::Cookbook::Custom::DBH';
    with 'DBIx::Cookbook::Util';
    
    has order_by => (
        isa => "Str",
        is  => "rw",
    );
    
    sub execute {
        my ( $self, $opt, $args ) = @_;
    
    =for comment
      my $sql=<<'EOSQL';
    SELECT * FROM film
    WHERE 
      ( DESCRIPTION LIKE '%drama' AND title LIKE 'a%' )
      OR title = 'BANG KWAI'
    EOSQL
    
      my $result = $self->connect->execute($sql);
    =cut
    
        #use DBI;
        #DBI->trace(1);
    
        my $result = $self->connect->select(
            table => 'film',
            where => [
                [
                    or => [
                        and => "LOWER(DESCRIPTION) LIKE '%drama%'",
                        "LOWER(title) LIKE 'a%'"
                    ],
                    "title = 'FISH OPUS'"
                ],
                {}
            ]
        );
    
        while ( my $row = $result->fetch_hash ) {
            warn $self->dumper($row);
        }
    }
    
    1;
    


