
=pod

=head1 NAME

DBIx::Cookbook::Recipe::Searching::fetch_single - fetch a single record

=head1 DESCRIPTION

Select a single record from the C<actor> table

Sample Usage:

 shell> ${orm}_cmd fetch_single # where orm is dbic, skinny, rose, etc.

=head1 RECIPES

=head2 DBIx::Class

    package DBIx::Cookbook::DBIC::Command::fetch_single;
    use Moose;
    extends qw(MooseX::App::Cmd::Command);
    
    use Data::Dump;
    
    sub execute {
      my ($self, $opt, $args) = @_;
    
      my $where = {};
      my $attr = {};
    
      my $rs = $self->app->schema->resultset('Actor')->search($where, $attr);
    
      my $row = $rs->single;
    
      my %data = $row->get_columns;
      warn Data::Dump::dump(\%data);
    
    }
    
    1;


=head2 DBIx::Class

    package DBIx::Cookbook::Custom::Command::fetch_single;
    use Moose;
    extends qw(MooseX::App::Cmd::Command);
    
    with 'DBIx::Cookbook::Custom::DBH';
    with 'DBIx::Cookbook::Util';
    
    has order_by => (
        isa => "Str",
        is  => "rw",
    );
    
    sub execute {
        my ( $self, $opt, $args ) = @_;
    
        my @attr = $opt->{order_by} ? ( sort_by => $opt->{order_by} ) : ();
    
        my $result = $self->connect->select( table => 'actor' );
    
        my $row = $result->fetch_hash_first;
        warn $self->dumper($row);
    
    }
    
    1;
    


